# Site/SEO settings
email: draguve@gmail.com
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics: "UA-157628838-1"

name: Ritwik Patil
title: Draguve
description: >
  This is Draguve's blog, I may put stuff i like here. 
url: https://www.draguve.wtf
twitter_username: draguve
default_img: /assets/images/seo.jpg
social:
  - name: twitter
    url: https://twitter.com/draguve
  - name: instagram
    url: https://www.instagram.com/draguve/
  - name: linkedin
    url: https://www.linkedin.com/in/ritwik-patil-aaa92013b/
  - name: github
    url: https://github.com/draguve

# Contact settings
contact_img: /assets/images/placeholder-28.jpg
formcarry: https://formcarry.com/s/x_AZ7-VYrBFx

# Disqus settings
disqus: draguve-wtf

# MailChimp settings
mailchimp_action: https://wtf.us17.list-manage.com/subscribe/post?u=7675218e2837a5b4b20710052&amp;id=19483e282c
mailchimp_input: b_7675218e2837a5b4b20710052_19483e282c

# Author settings
author:
  - name: Ritwik Patil  
    bio: Ritwik Patil was born and raised in India. He did his Bachelor of Technology in Electronics and Computer Engineering at Thapar University and now he's a Software Engineer at Samsung.
    url: https://www.draguve.wtf

# Pagination settings
pagination:
  enabled: true
  debug: false
  per_page: 12
  permalink: '/page/:num/'
  title: ':title'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
autopages:
  enabled: true
  categories:
    enabled: false
  collections:
    enabled: false
  tags:
    layouts: 
      - 'tag.html'
    title: 'Draguve'
    permalink: '/tag/:tag'
    slugify:
      mode: raw
      cased: true

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate-v2
  - jekyll-sitemap
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
  - vendor
